### ISSUE TITLE
Can't log into my account

### ISSUE THREAD

**Issue by amycatgirl** [h3poteto/fedistar#1395]
Hey there!

I can't sign to my account over at wetdry.world for some reason.

I assume that it should open the browser so I could authenticate with my account, but nothing has opened. Even after waiting for 10 minutes.

Other clients I've tried seem to not have issues logging into WDW

## Other (hopefully useful) information

Fedistar version: 1.9.0 (Linux x86_64, Appimage)
OS: Fedora Kinoite 39 (Using a custom image)

Note: I am launching the app through Gear Lever, which is a launcher/app manager for appimage files available on flathub.

**Comment by h3poteto** [comment]
> I assume that it should open the browser so I could authenticate with my account, but nothing has opened. Even after waiting for 10 minutes.

After you authenticate, what content is displayed?

**Comment by amycatgirl** [comment]
I can't authenticate

![Screenshot_20240320_101110](https://github.com/h3poteto/fedistar/assets/138383945/ea14c223-ccce-460e-a7d0-bd02a7e88a8c)

It gets stuck on this screen

**Comment by h3poteto** [comment]
Hmm, I can't reproduce it.
I suspect this error
>  no rows returned by a query that expected to return at least one row

but, I'm not sure.

Do you have accounts for other servers? Can you log in to other servers?

**Comment by amycatgirl** [comment]
Tried using another account on another server, no luck

**Comment by amycatgirl** [comment]
I am going to try and remove fedistar's data directory

Just to see if that fixes the issue

**Comment by amycatgirl** [comment]
Yeah, that did not fix the issue

**Comment by h3poteto** [comment]
That means the cause is not wetdry.world. You can't add any accounts. I will try adding more logs in the next release.

**Comment by h3poteto** [comment]
Can you please try 1.9.1?
https://github.com/h3poteto/fedistar/releases/tag/v1.9.1

This version supports log level config, please try
```
$ LOG_LEVEL=debug fedistar  
# If you are using AppImage, please try
$ LOG_LEVEL=debug fedistar_1.9.1_amd64.AppImage 
```

After that, debug level logs are recorded in the log file. Please share it.

**Comment by amycatgirl** [comment]
Sure, here is the log file
[fedistar.log](https://github.com/h3poteto/fedistar/files/14747907/fedistar.log)

**Comment by h3poteto** [comment]
Wow...... 
> no rows returned by a query that expected to return at least one row

this error is gone......
And there is no error.

**Comment by h3poteto** [comment]
Can you please try to open "Crash Report"? Help -> Crash Report in app menu.

**Comment by amycatgirl** [comment]
After selection the Crash Report button, the app crashes with the following error:

```
thread 'main' panicked at src/main.rs:648:22:
Failed to open the URL: Custom { kind: Other, error: "Launcher \"xdg-open\" \"https://fedistar.net/help#crash_reporting\" failed with ExitStatus(unix_wait_status(1024))" }
```

**Comment by h3poteto** [comment]
Ah, I see. Probably, `open` module is not working in your environment.

**Comment by h3poteto** [comment]
Can you please try this version?
https://github.com/h3poteto/fedistar/releases/tag/v1.9.2

**Comment by amycatgirl** [comment]
I tried using the version you provided, still no luck

I've provided the error and the logs below

```
thread 'tokio-runtime-worker' panicked at src/main.rs:108:55:
Failed to open the URL: Shell("failed to open: Scoped shell IO error: Launcher \"xdg-open\" \"https://wetdry.world/oauth/authorize?response_type=code&client_id=5OhdqSHYrjfakifrEcZA5RmL9dwDW9eVq1l0BcRLcPk&state=ihi5TtS8taZ8qzJhJ1ia6w&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=read+write+follow\" failed with ExitStatus(unix_wait_status(1024))")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[fedistar.log](https://github.com/h3poteto/fedistar/files/14791867/fedistar.log)

**Comment by h3poteto** [comment]
And I released a new version.
https://github.com/h3poteto/fedistar/releases/tag/v1.9.2

**Comment by amycatgirl** [comment]
Ok, I am able to get the authorization code now, but I still can't log in. After pasting the autorization code and pressing "Authorize", i get the following error from the webkit console:

```
[Error] error decoding response body: invalid value: integer `-1`, expected u32 at line 1 column 884
	(anonymous function) (index-599ff5d81100b1cf.js:1:96201)
```

**Comment by h3poteto** [comment]
Does it happen only wetdry.world? Or happens on other servers?
